name: iCalendar
version: !include "./VERSION"
synopsis: |-
  iCalendar data types, parser, and printer.
description: |-
  Data definitions, parsing and printing of the iCalendar format (RFC5545).
github: yurrriq/iCalendar
author:
- Christian Rødli Amble
- Eric Bailey
maintainer: Eric Bailey <eric@ericb.me>
copyright:
- (c) 2012 Tingtun AS
- (c) 2019 Eric Bailey
stability: experimental
category: Text
build-type: Simple
tested-with: GHC==8.6.5

library:
  exposed-modules:
  - Text.ICalendar.Types
  - Text.ICalendar.Parser
  - Text.ICalendar.Printer
  - Text.ICalendar
  other-modules:
  - Text.ICalendar.Parser.Common
  - Text.ICalendar.Parser.Components
  - Text.ICalendar.Parser.Content
  - Text.ICalendar.Parser.Parameters
  - Text.ICalendar.Parser.Properties
  - Paths_iCalendar
  dependencies:
  - base >=4.12 && <5
  - base64-bytestring ==1.0.*
  - bytestring >=0.10 && < 0.11
  - case-insensitive >=1.2
  - containers >= 0.6 && < 0.7
  - data-default >=0.7
  - mime >=0.4.0.2
  - mtl >=2.2
  - network >= 2.6 && < 2.9
  - network-uri >= 2.6
  - old-locale
  - parsec >=3.1
  - semigroups == 0.18.*
  - text >=1.2
  - time >=1.8
  ghc-options:
  - -Wall
  - -Werror
